### PR TITLE
Implement test

### PR DESCRIPTION
**Pull request by gdethier**
Hi Frederic,

I solved the exercise using stream operations only (without looking for the solution on the Web, I promise ;-)). IMHO I find this less readable than explicitly instantiating the map (which is done implicitly by the collector) but I guess it's a matter of taste...

Have a nice day,

Gérard

### CODE REVIEW

**Comment by frederic-gendebien** [comment]
> Hi Frederic,
> 
> I solved the exercise using stream operations only (without looking for the solution on the Web, I promise ;-)). IMHO I find this less readable than explicitly instantiating the map (which is done implicitly by the collector) but I guess it's a matter of taste...
> 
> Have a nice day,
> 
> Gérard

Thanks Gerard,

Indeed, this version is probably not o readable, but using: 
.collect(groupingBy(identity(), counting()))
you have your Map<String, Long> immediately

Cheers ;-)

**Comment by gdethier** [comment]
Well, I learned something. Thanks!

**Comment by frederic-gendebien** [comment]
> Well, I learned something. Thanks!

My pleasure!

**Comment by frederic-gendebien** [comment]
Closing for not showing the result ;-)

**Pull request closed without merging**
